version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: javax.enterprise:cdi-api
    versions:
    - "< 2.0.1"
    - ">= 2.0.0.a"
