#
# dependency-tracker (https://github.com/hazendaz/dependency-tracker)
#
# Copyright 2011-2020 Hazendaz.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of The Apache Software License,
# Version 2.0 which accompanies this distribution, and is available at
# https://www.apache.org/licenses/LICENSE-2.0.txt
#
# Contributors:
#     Hazendaz (Jeremy Landis).
#

name: Sonatype

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository_owner == 'hazendaz'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Deploy to Sonatype
        run: ./mvnw deploy -DskipTests -B --settings ./.mvn/settings.xml
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
